// src/vue/src/contact.vue
<script>
    var Store = require('./store');

    module.exports = {
        methods: {
            deleteContact: function(contact) {
                Store.deleteContact(contact, function(contact) {
                    this.$dispatch('DELETE_CONTACT_SUCCESS');
                }.bind(this));
            }
        }
    }
</script>

<template>
    <tr>
        <td>
            <a href="#/contacts/{{id}}">{{name}}</a>
        </td>
        <td>
            <a href="#/contacts/{{id}}/edit"><i class="fa fa-edit"></i></a>
        </td>
        <td>
            <button class="button-warning pure-button" v-on="click: deleteContact(this)">
                <i class="fa fa-remove"></i>
            </button>
        </td>
    </tr>
</template>

// src/react-flux/src/components/Contact.react.js
var React = require('react'),
    ReactPropTypes = React.PropTypes;

var Contact = React.createClass({

    propTypes: {
        contact: ReactPropTypes.object.isRequired
    },

    render: function() {

        var contact = this.props.contact;

        var url = {
            details: '#/contacts/' + contact.id,
            edit: '#/contacts/' + contact.id + '/edit'
        };

        return (
            <tr key={contact.id}>
                <td>
                    <a href={url.details}>{contact.name}</a>
                </td>
                <td>
                    <a href={url.edit}>
                        <i className="fa fa-edit"></i>
                    </a>
                </td>
                <td>
                    <button className="button-warning pure-button">
                        <i className="fa fa-remove"></i>
                    </button>
                </td>
            </tr>
        );
    }
});

module.exports = Contact;
