// src/react-flux/src/components/ContactDetails.react.js
var React = require('react'),
    Router = require('react-router'),
    Link = Router.Link,
    ReactPropTypes = React.PropTypes,
    ContactStore = require('../stores/ContactStore');

var Contact = React.createClass({

    mixins: [Router.State],

    getStateFromStore: function () {
        var id = this.getParams().id;
        return ContactStore.getContact(id)
    },

    getInitialState: function () {
        return this.getStateFromStore();
    },

    componentDidMount: function () {
        ContactStore.addChangeListener(this.updateContact);
    },

    componentWillUnmount: function () {
        ContactStore.removeChangeListener(this.updateContact);
    },

    componentWillReceiveProps: function () {
        this.setState(this.getStateFromStore());
    },

    updateContact: function () {
        this.setState(this.getStateFromStore());
    },

    render: function() {

        var contact = this.state || {};

        if(!contact.id) return null;

        return (
            <div>
                <dl>
                    <dt>{contact.name}</dt>
                    <dd>{contact.email}</dd>
                    <dd>{contact.phone}</dd>
                </dl>
                <Link to="contactEdit" params={contact} className="pure-button pure-button-primary">Edit</Link>
            </div>
        );
    }
});

module.exports = Contact;

// src/vue/src/contactDetails.vue
<script>
    var Store = require('./store');

    module.exports = {
        data: function() {
            return {
                params: {
                    currentContactId: null
                },
                contact: {}
            };
        },
        attached: function() {
            this.getContact();
        },
        methods: {
            getContact: function() {
                Store.getContact(this.params.currentContactId, function(contact) {
                    this.contact = contact;
                }.bind(this))
            }
        }

    };
</script>

<template>
    <div>
        <dl>
            <dt>{{contact.name}}</dt>
            <dd>{{contact.email}}</dd>
            <dd>{{contact.phone}}</dd>
        </dl>
        <a href="#/contacts/{{contact.id}}/edit" class="pure-button pure-button-primary">Edit</a>
    </div>
</template>
